name: server
description: A server app using the shelf package
version: 1.0.0

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.0
  drift: ^2.7.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.1.0
  drift_dev: ^2.3.0